// File generated by FlutterFire CLI.
// Replace this file by running: dart pub global run flutterfire_cli:flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web app: prefer a real `:web:` appId from Firebase Console → Project settings.
  // Until then, reuse the Android app registration for this project.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUTD9HoNb0y-faFmP0-t1UwJqCTSlh6DQ',
    appId: '1:526168154419:android:c302ee3a6a7aa59aa75e46',
    messagingSenderId: '526168154419',
    projectId: 'rumour-chatapp',
    authDomain: 'rumour-chatapp.firebaseapp.com',
    storageBucket: 'rumour-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUTD9HoNb0y-faFmP0-t1UwJqCTSlh6DQ',
    appId: '1:526168154419:android:c302ee3a6a7aa59aa75e46',
    messagingSenderId: '526168154419',
    projectId: 'rumour-chatapp',
    storageBucket: 'rumour-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'rumour-REPLACE_ME',
    storageBucket: 'rumour-REPLACE_ME.appspot.com',
    iosBundleId: 'app.rumour.rumour',
  );
}
